### ISSUE TITLE
Support Adding Stock WordPress Image

### ISSUE THREAD

**Issue by bearded-avenger** [AesopInteractive/lasso#12]
if the image is already existing and added from the backend post editor, and you load lasso and go to edit it, you can edit the image. need to support adding the image from with lasso, by always having the + icon there. 

no aesop == support for adding at least image
aesop == thats removed, aesop components loaded

**Comment by michaelbeil** [comment]
Well now, there we go.

**Comment by bearded-avenger** [comment]
done in 0.9.1

**Comment by michaelbeil** [comment]
Seems to be an issue when inserting an image as noted by rob.

"It looks like this is your culprit:

https://gist.github.com/robneu/546f33c386d34c0a576b#file-process-wpimg-js-L6

That’s in public/assets/js/src/process-wpimg.js

If you set up a fallback, I think you should be alright. Whenever an image
isn’t large enough for a “large” version to be generated, everything wigs
out. It also starts trying to fire the sidebar when you’ve set an image but
it can’t find a var with the image properties so an empty sidebar pops out
instead of the image edit modal. Some error handling in the function that
fires the modal might also be good."

**Comment by michaelbeil** [comment]
![screen capture on 2015-03-27 at 22-11-01](https://cloud.githubusercontent.com/assets/4752949/6879655/79a0aed0-d4ce-11e4-98ac-21d0ec9e67bd.gif)

**Comment by michaelbeil** [comment]
![screen shot 2015-03-27 at 21 48 48](https://cloud.githubusercontent.com/assets/4752949/6879737/975687b4-d4d4-11e4-8b82-6502806acac3.png)

**Comment by bearded-avenger** [comment]
this was fixed
